title: Streamdata Gallery Azure Cognitive Services
url: azure-cognitive-services.streamdata.gallery
tag: Azure Cognitive Services
markdown: kramdown
exclude: [".rvmrc", ".rbenv-version", "README.md", "Rakefile", "changelog.md", ".DS_Store"]
github_user: streamdata-gallery
github_repo: azure-cognitive-services
github_branch: master
collections:
  listings:
    output: true
    permalink: /listings/:path/
defaults:
  - scope:
      type: listings
    values:
      layout: listings
